name: Test

on:
  push:
    branches:
      - pre-dev
      - "feat**"
      - "fix**"
      - "job**"

env:
  AWS_EC2_METADATA_DISABLED: "true"
  BASE_FOLDER_NAME: shared-infra
  GIT_TERMINAL_PROMPT: 1
  PULUMI_BUCKET: vtechstudio-infrastructure-state
  PULUMI_CONFIG_PASSPHRASE: dummy

jobs:
  pulumi-sys-test:
    name: Pulumi System Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TO_CLONE_REPO }}
      - name: Set Environments
        run: |
          echo "${{ secrets.DEV_ENV_FILE_EU_CENTRAL_1 }}" > $GITHUB_ENV

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.DEPLOYER_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEPLOY_REGION }}

      - uses: actions/setup-go@v4
        name: Setup Go
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set token for Go
        env:
          GO_TOKEN: ${{ secrets.GO_TOKEN }}
        run: |
          export GOPRIVATE=github.com/amplifon-x
          cat > /home/runner/.netrc << EOF
            machine github.com login ${GO_TOKEN}
          EOF

      - name: Login to Pulumi backend
        run: pulumi login s3://${{ env.PULUMI_BUCKET }}

      - name: Select or create stack
        run: |
          cd infrastructure
          pulumi stack select organization/${{ env.TF_VAR_project_prefix }}/${{ env.TF_VAR_env }} || pulumi stack init organization/${{ env.TF_VAR_project_prefix }}/${{ env.TF_VAR_env }}
          pulumi stack --show-urns

      - name: Pulumi preview
        run: |
          cd infrastructure
          pulumi refresh --yes
          pulumi --stack organization/${{ env.TF_VAR_project_prefix }}/${{ env.TF_VAR_env }} preview
          pulumi stack --show-urns
